del "..\proj\game_vs11.sdf"
del /a "..\proj\game_vs11.v11.suo"
del "..\proj\visualstudio\engine\engine_vs11.vcxproj.user"
del "..\proj\visualstudio\game\game_vs11.vcxproj.user"
del "..\proj\visualstudio\support\murmurhash\murmurhash_vs11.vcxproj.user"
del "..\proj\visualstudio\support\tinyxml2\tinyxml2_vs11.vcxproj.user"
del "..\lib\engine.lib"
del "..\lib\engined.lib"
del "..\lib\murmurhash.lib"
del "..\lib\murmurhashd.lib"
del "..\lib\tinyxml2.lib"
del "..\lib\tinyxml2d.lib"
rd /s /q "..\proj\visualstudio\debug"
rd /s /q "..\proj\visualstudio\release"
rd /s /q "..\bin"
rd /s /q "..\proj\visualstudio\engine\include"
rd /s /q "..\proj\visualstudio\engine\src"
rd /s /q "..\proj\visualstudio\game\src"
rd /s /q "..\proj\visualstudio\game\include"
rd /s /q "..\proj\visualstudio\support\murmurhash\include"
rd /s /q "..\proj\visualstudio\support\murmurhash\src"
rd /s /q "..\proj\visualstudio\support\tinyxml2\include"
rd /s /q "..\proj\visualstudio\support\tinyxml2\src"
